import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "../globals.css";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Nice Tour - Your Partner Tour",
  description: "Generated by create next app",
};

export default function LandingHomeLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${fontSans.className} font-poppins text-white bg-flysha-black`}
      >
        {children}
      </body>
    </html>
  );
}
